import { createClient } from "@/utils/supabase/server";
import { NextResponse } from "next/server";

const reportPrompts = {
  carbon_footprint: "Generate a detailed Carbon Footprint Assessment report for the following company. Include sections: Executive Summary, Scope 1/2/3 Emissions Overview, Emission Sources Analysis, Reduction Recommendations, and Next Steps.",
  esg_strategy: "Generate a comprehensive ESG Strategy Report for the following company. Include sections: Executive Summary, Environmental Assessment, Social Impact Analysis, Governance Review, Material Topics, Strategy Recommendations, and Implementation Roadmap.",
  csrd_gap: "Generate a CSRD Gap Analysis report for the following company. Include sections: Executive Summary, Current Reporting Status, ESRS Standards Assessment, Gap Identification, Priority Actions, and Compliance Timeline.",
  supply_chain: "Generate a Supply Chain Sustainability Assessment for the following company. Include sections: Executive Summary, Supply Chain Mapping, Scope 3 Emissions Analysis, Supplier Risk Assessment, Sustainability Opportunities, and Action Plan.",
  circular_economy: "Generate a Circular Economy Analysis for the following company. Include sections: Executive Summary, Current Linear Processes, Circularity Opportunities, Material Flow Analysis, Business Model Innovation, and Implementation Roadmap.",
};

export async function POST(request) {
  let supabase, user;
  try {
    supabase = await createClient();
    const { data } = await supabase.auth.getUser();
    user = data?.user;
  } catch {
    return NextResponse.json({ error: "Supabase not configured" }, { status: 500 });
  }

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { name, type, description, lang } = await request.json();

  const prompt = reportPrompts[type] || reportPrompts.carbon_footprint;
  const langName = { en: "English", fr: "French", ar: "Arabic" }[lang] || "English";

  // Generate AI report content (placeholder - connects to AI API)
  const reportContent = generatePlaceholderReport(name, type, description, langName);

  const { data, error } = await supabase
    .from("esg_reports")
    .insert({
      user_id: user.id,
      name,
      type,
      description,
      content: reportContent,
      status: "completed",
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json(data);
}

function generatePlaceholderReport(name, type, description, lang) {
  return `# ${name}

## Executive Summary
This ESG report has been generated for your organization based on the provided information.
A comprehensive analysis would require connection to an AI API (Claude, GPT, etc.) for full report generation.

## Company Profile
${description}

## Report Type: ${type}

## Key Findings
- Initial assessment based on provided company description
- Detailed analysis requires additional data collection
- Industry benchmarking recommended

## Recommendations
1. Conduct a detailed Scope 1, 2, and 3 emissions inventory
2. Establish baseline metrics for ESG performance tracking
3. Develop a stakeholder engagement plan
4. Set science-based targets aligned with SBTi
5. Implement regular monitoring and reporting frameworks

## Next Steps
- Schedule a consultation with Systain Advisory for a detailed assessment
- Contact: contact@systain-algeria.com

---
*Generated by Systain Advisory ESG Report Generator*
*For a comprehensive, certified assessment, please contact our team.*
`;
}
